### ISSUE TITLE
How is memory usage handled for image resizing

### ISSUE THREAD

**Issue by AndreasSchmid1** [maxisam/ngx-progressive-image-loader#5]
First: Thanks for the great repo.

I have a question regarding memory usage when loading images via this library AND using the max-width/height options in your excample.

Suppose I'm loading a 2000x2000 pixel image with the 200x200 option with maximum width and height. Is the large image kept in memory and only scaled or is a 200x200 image created and the large image deleted?

thank you very much for help.

**Comment by maxisam** [comment]
this library doesn't involve any image creation, so it will keep the original image in memory.
