### ISSUE TITLE
Possible to use a flexible imageRatio (none stretch)

### ISSUE THREAD

**Issue by AndreasSchmid1** [maxisam/ngx-progressive-image-loader#7]
I try to use progressive images to load thumbnails which can be at any aspect ratio. Before using ngx-progressive-image-loader I was able to implement this successfully with Flexbox.

` .thumbnailContainer {
    flex: 2 ;
    overflow: auto;
    position: relative;
    
} 
  img {
    position: absolute;
    top: 0; bottom:0; left: 0; right:0;
    margin: auto;
    max-width: 100%;
    max-height: 100%;
}`

`<div class="thumbnailContainer" fxLayout="column">
                      <img  src="{{ThumbnailLink}}"   /> 
                  </div>`

My code matched to the lib looks like this. Unfortunately it doesn't work because the images get stretched to a specific aspect ratio

`  <ngx-progressive-image-loader class="thumbnailContainer" fxLayout="column" >
                    <div class="thumbnailContainer" fxLayout="column">
                      <img  [src]="slide.SlideThumbnailLink" alt="" ngxProgressiveImage /> 
                    </div>
                  </ngx-progressive-image-loader>`

Thank you very much for help in advance.

**Comment by maxisam** [comment]
i don't think it will work for your case unless you know the ratio before hand.

**Comment by maxisam** [comment]
Well, I think it is more like a limitation. Currently, I don't see a way to do it.

**Comment by AndreasSchmid1** [comment]
ok thanks for your feedback!

**Comment by maxisam** [comment]
If you figure out a way, feel free to make a PR. Thx.

**Comment by AndreasSchmid1** [comment]
ok yes. i found out that there is a lib called "ng-lazyload-image" which is able to do it.
